// Generated by Selenium IDE

import java.util.List;
import java.util.Map;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class SneakerRaffleBot implements Runnable{

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    private List<String>  emailAdresses;

    public SneakerRaffleBot(List<String> emailAdresses) {
        this.emailAdresses = emailAdresses;
    }


    public void run(){

        for (String emailAdress : this.emailAdresses) {
            try {
                ChromeOptions options = new ChromeOptions();
                options.addArguments("--window-size=800,400");
                this.driver = new ChromeDriver(options);
                this.js = (JavascriptExecutor) this.driver;
                WebDriverWait wait = new WebDriverWait(this.driver, 3);
                this.driver.get("https://www.adidas.at/yeezy");

                (new WebDriverWait(driver, 10)).until(ExpectedConditions.presenceOfElementLocated(By.name("minimumAge")));
                WebElement minimumAge = driver.findElement(By.name("minimumAge"));
                minimumAge.click();
                WebElement email = driver.findElement(By.id("cs-input-email"));
                email.sendKeys(emailAdress);
                WebElement submit = driver.findElement(By.cssSelector(".gl-cta:nth-child(1)"));
                submit.click();

                wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".cstudio-component-thank-you")));

            }
            catch (Exception e){
                e.printStackTrace();
            }
            this.driver.quit();
        }

    }


}
