// Generated by Selenium IDE
import com.github.javafaker.Faker;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class SneakerRaffleBot implements Runnable{

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    final static int AMOUNT_EMAIL_ADRESSES = 10;
    private List<String>  emailAdresses;

    public SneakerRaffleBot(List<String> emailAdresses) {
        this.emailAdresses = emailAdresses;
    }


    public void run(){

        for (String emailAdress : this.emailAdresses) {
            try {
                ChromeOptions options = new ChromeOptions();
                //options.addArguments("--headless");
                this.driver = new ChromeDriver(options);
                this.js = (JavascriptExecutor) this.driver;
                WebDriverWait wait = new WebDriverWait(this.driver, 3);
                this.driver.get("https://www.adidas.at/yeezy");
                this.driver.manage().window().setSize(new Dimension(1908, 848));


                Actions actions = new Actions(this.driver);
//              actions.moveToElement(this.driver.findElement(By.id("cs-input-email")))
//                    .pause(1000)
//                    .click()
//                    .build()
//                    .perform();

                //WebDriverWait waitForUsername = new WebDriverWait(driver, 5000);
                //waitForUsername.until(ExpectedConditions.(By.id("cs-input-email")));
                actions.pause(2000).build().perform();
                JavascriptExecutor jse = (JavascriptExecutor)driver;
                jse.executeScript("document.getElementById('cs-input-email').value = 'eineEmailAdresse';");

                jse.executeScript("document.getElementsByName('minimumAge')[0].click();");

                jse.executeScript("document.querySelector('.gl-cta:nth-child(1)').click();");

                wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".cstudio-component-thank-you")));

            }
            catch (Exception e){
                e.printStackTrace();
            }
            this.driver.quit();
        }

    }


}
